name: 🙋 Student Question
description: Ask a question about course content, modules, or implementation
title: "[Question] "
labels: ["question", "student-help"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the Vue Full-Stack Course! Please provide as much detail as possible to help us assist you.

  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Which module is your question about?
      options:
        - "Module 1: Development Environment Setup"
        - "Module 2: Frontend Foundation with Vue 3" 
        - "Module 3: Form Handling and Validation"
        - "Module 4: Backend API Development"
        - "Module 5: Nuxt Migration & Setup"
        - "Module 6: Database Integration with Nuxt"
        - "Module 7: Advanced Authentication with Better-Auth"
        - "Module 8: Advanced Frontend Features"
        - "Module 9: Testing & Quality Assurance"
        - "Module 10: Production Deployment & Optimization"
        - "General Course Question"
    validations:
      required: true

  - type: dropdown
    id: section
    attributes:
      label: Course Section
      description: Are you in the Beginner or Advanced section?
      options:
        - "🎯 Beginner Section (Modules 1-4)"
        - "🚀 Advanced Section (Modules 5-10)"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: Describe your question in detail
      placeholder: |
        Please be specific about:
        - What you're trying to accomplish
        - What you expected to happen
        - What actually happened (if applicable)
        - Any error messages you're seeing
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Snippet (if applicable)
      description: Share relevant code that's causing issues
      render: javascript
      placeholder: |
        // Paste your code here
        // Include file names and line numbers if helpful

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: |
        - What documentation have you already consulted?
        - What have you tried so far?
        - Screenshots of errors (if applicable)
        - Your development environment (OS, Node version, etc.)

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you've completed these steps
      options:
        - label: I have read the relevant module documentation
          required: true
        - label: I have checked the module's troubleshooting section
          required: true
        - label: I have searched existing issues for similar questions
          required: true
        - label: I have provided enough detail for others to understand my question
          required: true