# GitHub Pages configuration
title: Vue Full-Stack Development Course
description: A comprehensive Vue.js full-stack development course with 10 modules covering Vue 3, Nuxt 3, authentication, testing, and deployment
url: https://ge-hall.github.io/vue-fullstack-course

# Jekyll configuration
markdown: kramdown
highlighter: rouge
# Disable theme to prevent CSS conflicts
# theme: minima

# Kramdown configuration for better markdown processing
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false

# Exclude files
exclude:
  - node_modules/
  - .git/
  - .github/
  - README.md
  - package*.json
  - "*.log"

# Include files
include:
  - _config.yml
  - modules/
  - mockups/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections for better organization
collections:
  modules:
    output: true
    permalink: /:collection/:name/
  mockups:
    output: true
    permalink: /:collection/:name/

# Defaults for collections
defaults:
  - scope:
      path: ""
      type: "modules"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "mockups"
    values:
      layout: "default"

# SEO
author: Vue Full-Stack Course
twitter:
  username: vue_fullstack
  card: summary_large_image

social:
  name: Vue Full-Stack Course
  links:
    - https://github.com/ge-hall/vue-fullstack-course

# Google Analytics (add your tracking ID if needed)
# google_analytics: G-XXXXXXXXXX